server:
  port: 10012
  ssl:
    enabled: true
    client-auth: need
    key-alias: enrolment-store
    key-store-password: r4T#OP@#Ybf1M_vN
    key-store: classpath:keystore.p12
    key-store-type: JKS
    trust-store-type: PKCS12
    trust-store-password: jJ$ZfxLlV##WweGk
    trust-store: classpath:ca.truststore

eureka:
  client:
    serviceUrl:
      defaultZone: https://localhost:10003/eureka/

spring:
  application:
    name: enrolment
  config:
    import: optional:configserver:https://localhost:10004/
  datasource:
    url: jdbc:mysql://localhost:3306/db_enrolement?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password:
    generate-unique-name: false
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
