server:
  port: 10014
  ssl:
    enabled: true
    client-auth: need
    key-alias: account-service-store
    key-store-password: ZF@iCDnwx64Br3p2
    key-store: classpath:keystore.p12
    key-store-type: JKS
    trust-store-type: PKCS12
    trust-store-password: 9@M6SXfcmpxhvTOf
    trust-store: classpath:ca.truststore

eureka:
  client:
    serviceUrl:
      defaultZone: https://localhost:10003/eureka/

spring:
  application:
    name: account-service
  config:
    import: optional:configserver:https://localhost:10004/
  datasource:
    url: jdbc:mysql://localhost:3306/db_service?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password:
    generate-unique-name: false
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

