server:
  port: 10014
  ssl:
    enabled: true
    client-auth: need
    key-alias: account-service-store
    key-store-password: ZF@iCDnwx64Br3p2
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    trust-store-type: PKCS12
    trust-store-password: 9@M6SXfcmpxhvTOf
    trust-store: classpath:ca.truststore

eureka:
  client:
    serviceUrl:
      defaultZone: http://default_user:user_pass2002@localhost:10003/eureka/

spring:
  application:
    name: account-service
  config:
    import: configserver:https://localhost:10004/
  datasource:
    url: jdbc:mysql://localhost:3306/pg_service?createDatabaseIfNotExist=true&serverTimezone=UTC&verifyServerCertificate=false&useSSL=true&requireSSL=true&clientCertificateKeyStoreUrl=file:dbkeystore.p12&clientCertificateKeyStorePassword=2hIDML8pPnli1jTs&trustCertificateKeyStoreUrl=file:db-ca.truststore&trustCertificateKeyStorePassword=mVV6eXFudmqORAoU
    username: paymentgateway
    password: oEij4yKJOMlUHGMe
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


