server:
  port: 10013
  ssl:
    enabled: true
    client-auth: need
    key-alias: account-organisation-storee
    key-store-password: eEAHbPdh@PCYieHi
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    trust-store-type: PKCS12
    trust-store-password: zPqdWagQ_b67yBc#
    trust-store: classpath:ca.truststore

eureka:
  client:
    serviceUrl:
      defaultZone: http://default_user:user_pass2002@localhost:10003/eureka/

spring:
  application:
    name: account-organisation
  config:
    import: optional:configserver:https://localhost:10004/
  datasource:
    url: jdbc:mysql://localhost:3306/pg_organisation?createDatabaseIfNotExist=true&serverTimezone=UTC&verifyServerCertificate=false&useSSL=true&requireSSL=true&clientCertificateKeyStoreUrl=file:dbkeystore.p12&clientCertificateKeyStorePassword=2hIDML8pPnli1jTs&trustCertificateKeyStoreUrl=file:db-ca.truststore&trustCertificateKeyStorePassword=mVV6eXFudmqORAoU
    username: paymentgateway
    password: oEij4yKJOMlUHGMe
    generate-unique-name: false
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

