server:
  port: 10003
#   ssl:
#     enabled: true
#     protocol: TLS
#     client-auth: need
#     key-store-password: wDCBFYHzkQF##n97
#     key-store: classpath:keystore.p12
#     key-alias: discovery-store
#     key-store-type: JKS
#     trust-store: classpath:ca.truststore
#     trust-store-type: PKCS12
#     trust-store-password: w_hjgdFOB5q5HF9B

spring:
  application:
    name: discovery
  security:
    basic:
      enabled: true
    user:
      name: default_user
      password: user_pass2002

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF

