server:
  port: 10002
#  ssl:
#    enabled: true
#    protocol: TLS
#    client-auth: none
#    key-alias: gateway-store
#    key-store: classpath:keystore.p12
#    key-store-type: PKCS12
#    key-store-password: Tn6@shdgt#lsRSjd_89
#    trust-store: classpath:ca.truststore
#    trust-store-password: A@Pw0sdt#u@js
#    trust-store-type: PKCS12

eureka:
  client:
    serviceUrl:
      defaultZone: http://default_user:user_pass2002@localhost:10003/eureka/
spring:
  application:
    name: httpgateway
    config:
      import: optional:configserver:https://localhost:10004/
  cloud:
    gateway:
      httpclient:
        ssl:
          key-store: classpath:keystore.p12
          key-store-type: PKCS12
          key-store-password: Tn6@shdgt#lsRSjd_89
          trusted-x509-certificates:
            - http-gateway-ca-rootCA.crt
            - account-organisation-ca-rootCA.crt
            - account-service-ca-rootCA.crt
            - account-souscription-ca-rootCA.crt
            - audit-ca-rootCA.crt
            - config-service-ca-rootCA.crt
            - discovery-ca-rootCA.crt
            - enrolment-ca-rootCA.crt
            - logging-ca-rootCA.crt
            - ussd-gateway-ca-rootCA.crt
      routes:
        - id: audit
          uri: https://localhost:10010
          predicates:
            - Path=/auditsrv/**
          filters:
#            - EncryptDecryptFilter
            - RewritePath=/auditsrv(?<segment>/?.*), $\{segment}
        - id: config
          uri: https://localhost:10004
          predicates:
            - Path=/configsrv/**
          filters:
#            - EncryptDecryptFilter
            - RewritePath=/configsrv(?<segment>/?.*), $\{segment}
        - id: account-organisation
          uri: https://localhost:10013
          predicates:
            - Path=/organisationsrv/**
          filters:
#            - EncryptDecryptFilter
            - RewritePath=/organisationsrv(?<segment>/?.*), $\{segment}
        - id: logging
          uri: https://localhost:10011
          predicates:
            - Path=/loggingsrv/**
          filters:
#            - EncryptDecryptFilter
            - RewritePath=/loggingsrv(?<segment>/?.*), $\{segment}
        - id: subscription
          uri: https://localhost:10017
          predicates:
            - Path=/subscriptionsrv/**
          filters:
#            - EncryptDecryptFilter
            - RewritePath=/subscriptionsrv(?<segment>/?.*), $\{segment}
        - id: account-services
          uri: https://localhost:10014
          predicates:
            - Path=/servicessrv/**
          filters:
#            - EncryptDecryptFilter
            - RewritePath=/servicessrv(?<segment>/?.*), $\{segment}
