server:
  port: 10016
  ssl:
    enabled: true
    client-auth: need
    key-alias: ussd-gateway-store
    key-store-password: GyC5XaEpiymw4aA4
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    trust-store-type: PKCS12
    trust-store-password: knD9ErE8DuxTgPCG
    trust-store: classpath:ca.truststore

eureka:
  client:
#     tls:
#       enabled: true
#       key-store-password: GyC5XaEpiymw4aA4
#       key-store: classpath:keystore.p12
#       key-store-type: JKS
#       key-password: iHBA_CtpuEBE@Oty
#       trust-store-type: PKCS12
#       trust-store-password: knD9ErE8DuxTgPCG
#       trust-store: classpath:ca.truststore
    serviceUrl:
      defaultZone: http://default_user:user_pass2002@localhost:10003/eureka/

spring:
  application:
    name: ussdgateway
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pg_ussdgateway?createDatabaseIfNotExist=true&serverTimezone=UTC&verifyServerCertificate=false&useSSL=true&requireSSL=true&clientCertificateKeyStoreUrl=file:dbkeystore.p12&clientCertificateKeyStorePassword=2hIDML8pPnli1jTs&trustCertificateKeyStoreUrl=file:db-ca.truststore&trustCertificateKeyStorePassword=mVV6eXFudmqORAoU
    username: paymentgateway
    password: oEij4yKJOMlUHGMe
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
    show-sql: true
serverTimeZone: UTC
